CREATE PIPE "SPOT_PRICE"."PUBLIC".LOAD_PRICE AUTO_INGEST = TRUE AS 
COPY INTO "SPOT_PRICE"."PUBLIC"."PRICE" 
  ("ASOF_DATE", "AVAILABILITY_ZONE", "INSTANCE_TYPE", 
   "PRODUCT_DESCRIPTION", "SPOT_PRICE", "TIME_STAMP") 
FROM 
(
  SELECT CURRENT_TIMESTAMP, $1, $2, $3, $4, $5
  FROM @"SPOT_PRICE"."PUBLIC"."PRICE_STAGE" 
  ( FILE_FORMAT => "SPOT_PRICE"."PUBLIC"."REGION_PRICES")
);